/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedNaoConformidadesRouteImport } from './routes/_authenticated/nao-conformidades'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedAuditoresRouteImport } from './routes/_authenticated/auditores'
import { Route as AuthenticatedAreasRouteImport } from './routes/_authenticated/areas'
import { Route as AuthenticatedAuditoriasIndexRouteImport } from './routes/_authenticated/auditorias.index'
import { Route as AuthenticatedAuditoriasNovaRouteImport } from './routes/_authenticated/auditorias.nova'
import { Route as AuthenticatedAuditoriasIdRouteImport } from './routes/_authenticated/auditorias.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNaoConformidadesRoute =
  AuthenticatedNaoConformidadesRouteImport.update({
    id: '/nao-conformidades',
    path: '/nao-conformidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoresRoute = AuthenticatedAuditoresRouteImport.update({
  id: '/auditores',
  path: '/auditores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAreasRoute = AuthenticatedAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriasIndexRoute =
  AuthenticatedAuditoriasIndexRouteImport.update({
    id: '/auditorias/',
    path: '/auditorias/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriasNovaRoute =
  AuthenticatedAuditoriasNovaRouteImport.update({
    id: '/auditorias/nova',
    path: '/auditorias/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriasIdRoute =
  AuthenticatedAuditoriasIdRouteImport.update({
    id: '/auditorias/$id',
    path: '/auditorias/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/auditores': typeof AuthenticatedAuditoresRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/nao-conformidades': typeof AuthenticatedNaoConformidadesRoute
  '/auditorias/$id': typeof AuthenticatedAuditoriasIdRoute
  '/auditorias/nova': typeof AuthenticatedAuditoriasNovaRoute
  '/auditorias/': typeof AuthenticatedAuditoriasIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/auditores': typeof AuthenticatedAuditoresRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/nao-conformidades': typeof AuthenticatedNaoConformidadesRoute
  '/': typeof AuthenticatedIndexRoute
  '/auditorias/$id': typeof AuthenticatedAuditoriasIdRoute
  '/auditorias/nova': typeof AuthenticatedAuditoriasNovaRoute
  '/auditorias': typeof AuthenticatedAuditoriasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/areas': typeof AuthenticatedAreasRoute
  '/_authenticated/auditores': typeof AuthenticatedAuditoresRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/nao-conformidades': typeof AuthenticatedNaoConformidadesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/auditorias/$id': typeof AuthenticatedAuditoriasIdRoute
  '/_authenticated/auditorias/nova': typeof AuthenticatedAuditoriasNovaRoute
  '/_authenticated/auditorias/': typeof AuthenticatedAuditoriasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/areas'
    | '/auditores'
    | '/historico'
    | '/nao-conformidades'
    | '/auditorias/$id'
    | '/auditorias/nova'
    | '/auditorias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/areas'
    | '/auditores'
    | '/historico'
    | '/nao-conformidades'
    | '/'
    | '/auditorias/$id'
    | '/auditorias/nova'
    | '/auditorias'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/areas'
    | '/_authenticated/auditores'
    | '/_authenticated/historico'
    | '/_authenticated/nao-conformidades'
    | '/_authenticated/'
    | '/_authenticated/auditorias/$id'
    | '/_authenticated/auditorias/nova'
    | '/_authenticated/auditorias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nao-conformidades': {
      id: '/_authenticated/nao-conformidades'
      path: '/nao-conformidades'
      fullPath: '/nao-conformidades'
      preLoaderRoute: typeof AuthenticatedNaoConformidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditores': {
      id: '/_authenticated/auditores'
      path: '/auditores'
      fullPath: '/auditores'
      preLoaderRoute: typeof AuthenticatedAuditoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/areas': {
      id: '/_authenticated/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AuthenticatedAreasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditorias/': {
      id: '/_authenticated/auditorias/'
      path: '/auditorias'
      fullPath: '/auditorias/'
      preLoaderRoute: typeof AuthenticatedAuditoriasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditorias/nova': {
      id: '/_authenticated/auditorias/nova'
      path: '/auditorias/nova'
      fullPath: '/auditorias/nova'
      preLoaderRoute: typeof AuthenticatedAuditoriasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditorias/$id': {
      id: '/_authenticated/auditorias/$id'
      path: '/auditorias/$id'
      fullPath: '/auditorias/$id'
      preLoaderRoute: typeof AuthenticatedAuditoriasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAreasRoute: typeof AuthenticatedAreasRoute
  AuthenticatedAuditoresRoute: typeof AuthenticatedAuditoresRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedNaoConformidadesRoute: typeof AuthenticatedNaoConformidadesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAuditoriasIdRoute: typeof AuthenticatedAuditoriasIdRoute
  AuthenticatedAuditoriasNovaRoute: typeof AuthenticatedAuditoriasNovaRoute
  AuthenticatedAuditoriasIndexRoute: typeof AuthenticatedAuditoriasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAreasRoute: AuthenticatedAreasRoute,
  AuthenticatedAuditoresRoute: AuthenticatedAuditoresRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedNaoConformidadesRoute: AuthenticatedNaoConformidadesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAuditoriasIdRoute: AuthenticatedAuditoriasIdRoute,
  AuthenticatedAuditoriasNovaRoute: AuthenticatedAuditoriasNovaRoute,
  AuthenticatedAuditoriasIndexRoute: AuthenticatedAuditoriasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
